// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUvP3UTy4rEFDUogn1z0u44ZixySkjCaw',
    appId: '1:397992760905:web:4dfb3c8ebc37033fc5d198',
    messagingSenderId: '397992760905',
    projectId: 'bainada-brothers-144ae',
    databaseURL: 'https://bainada-brothers-144ae-default-rtdb.firebaseio.com',
    authDomain: 'bainada-brothers-144ae.firebaseapp.com',
    storageBucket: 'bainada-brothers-144ae.firebasestorage.app',
    measurementId: 'G-MV8ZQ843Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCJBKvNMNy8CgaD7X98OGavA_nqVma144',
    appId: '1:397992760905:android:9d8165025c25ac9cc5d198',
    messagingSenderId: '397992760905',
    projectId: 'bainada-brothers-144ae',
    databaseURL: 'https://bainada-brothers-144ae-default-rtdb.firebaseio.com',
    storageBucket: 'bainada-brothers-144ae.firebasestorage.app',
  );
}
